{% set name = "finesse" %}
{% set version = "3.0a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finesse-{{ version }}.tar.gz
  sha256: bbaaaaa013aedd104635c069d606b0e1ba3935a25313a061a570d7e7031e9d16
  patches:
    # declare MS_WIN64 for min64 compiler
    - MS_WIN64.patch  # [win]

build:
  number: 0
  skip: true   # [py<38]
  entry_points:
    - kat3 = finesse.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    # extras for cross-compiling
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cython
    - libpython  # [win]
    - numpy 1.20  # [py<310]
    - numpy  # [py>=310]
    - pip
    - python
    - scipy >=1.4
    - setuptools  # [not win]
    - setuptools-scm
    - tqdm
    - wheel
    # work around missing ucrt library
    - setuptools <59.2.0  # [win]
    - setuptools-scm
    - suitesparse
  run:
    - click >=7.1
    - click-default-group >=1.2.2
    - control >=0.9
    - deprecated >=1.2
    - h5py >=3.0
    - matplotlib-base >=3.5
    - more-itertools
    - networkx >=2.4
    - {{ pin_compatible('numpy') }}
    - pyspellchecker >=0.6
    - python
    - scipy >=1.4
    - sly >=0.4
    - sympy >=1.6
    - tabulate >=0.8.7
    - tqdm

test:
  requires:
    - faker
    - hypothesis
    - pip
    - pytest
  source_files:
    - tests/
  imports:
    - finesse
    - finesse.analysis
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest tests/
    # check entry points
    - kat3 --help

about:
  home: https://www.gwoptics.org/finesse
  dev_url: https://git.ligo.org/finesse/finesse3.git
  doc_url: https://finesse.docs.ligo.org/finesse3/
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: A simulation tool for modelling laser interferometers
  description: |
    Finesse 3 is a Python based interferometer simulation software.

extra:
  recipe-maintainers:
    - danielbrown2
    - duncanmmacleod
    - freise
