{% set name = "finesse" %}
{% set version = "3.0a8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finesse-{{ version }}.tar.gz
  sha256: f310acd0843a4e68baf77bec83d22040a076db17e8cb462a3a032c2d04ce9bcb
  patches:
    # force windows cythonize
    - force_cythonize.patch  # [win]

build:
  number: 1
  skip: true  # [py<38]
  entry_points:
    - kat3 = finesse.__main__:cli

requirements:
  build:
    - {{ compiler('c') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    # extras for cross-compiling
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cython
    - libpython  # [win]
    - numpy
    - pip
    - python
    - scipy >=1.4
    - setuptools
    - setuptools-scm
    - tqdm
    - wheel
    - suitesparse
    - quantiphy
  run:
    - cython
    - click >=7.1
    - click-default-group >=1.2.2
    - control >=0.9
    - deprecated >=1.2
    - h5py >=3.0
    - matplotlib-base >=3.5
    - more-itertools >=8.7
    - networkx >=2.4
    - {{ pin_compatible('numpy') }}
    - pyspellchecker >=0.6
    - python
    - scipy >=1.4
    - sly >=0.4
    - sympy >=1.6
    - tabulate >=0.8.7
    - tqdm
    - quantiphy

test:
  requires:
    - faker
    - hypothesis
    - pip
    - pytest
  source_files:
    - tests/
  imports:
    - finesse
    - finesse.analysis
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - kat3 --help
    # run unit tests
    - python -m pytest tests --import-mode=importlib

about:
  home: https://www.gwoptics.org/finesse
  dev_url: https://git.ligo.org/finesse/finesse3.git
  doc_url: https://finesse.docs.ligo.org/finesse3/
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: A simulation tool for modelling laser interferometers
  description: |
    Finesse 3 is a Python based interferometer simulation software.

extra:
  recipe-maintainers:
    - danielbrown2
    - duncanmmacleod
    - freise
