{% set name = "finesse" %}
{% set version = "3.0a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finesse-{{ version }}.tar.gz
  sha256: a78c6ab43de6a23c97e55ec6238389d11de419ff1310a3c8b36a23e7a9fba99e
  patches:
    - cc_not_in_docker.patch # See https://gitlab.com/ifosim/finesse/finesse3/-/issues/546 should have been fixed for a7

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - kat3 = finesse.__main__:cli
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }} 
    - libgomp  # [linux]
    - llvm-openmp  # [osx and arm64]
    # extras for cross-compiling
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy 1.20                          # [py<310 and build_platform != target_platform]
    - numpy                               # [py>=310 and build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cython
    - libpython  # [win]
    - numpy 1.20  # [py<310]
    - numpy  # [py>=310]
    - pip
    - python
    - scipy >=1.4
    - setuptools
    - setuptools-scm
    - tqdm
    - wheel
    - setuptools-scm
    - suitesparse
  run:
    - click >=7.1
    - click-default-group >=1.2.2
    - control >=0.9
    - deprecated >=1.2
    - h5py >=3.0
    - matplotlib-base >=3.5
    - more-itertools
    - networkx >=2.4
    - {{ pin_compatible('numpy') }}
    - pyspellchecker >=0.6
    - python
    - scipy >=1.4
    - sly >=0.4
    - sympy >=1.6
    - tabulate >=0.8.7
    - tqdm
    - quantiphy

test:
  requires:
    - faker
    - hypothesis
    - pip
    - pytest
    - cython
    - control <=0.9.2 # using greater than this seems to fail pip check tests as version is 0.0.0??
  source_files:
    - tests/
  imports:
    - finesse
    - finesse.analysis
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest tests/
    # check entry points
    - kat3 --help

about:
  home: https://www.gwoptics.org/finesse
  dev_url: https://git.ligo.org/finesse/finesse3.git
  doc_url: https://finesse.docs.ligo.org/finesse3/
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: A simulation tool for modelling laser interferometers
  description: |
    Finesse 3 is a Python based interferometer simulation software.

extra:
  recipe-maintainers:
    - danielbrown2
    - duncanmmacleod
    - freise
