{% set name = "finesse" %}
{% set version = "3.0a29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finesse-{{ version }}.tar.gz
  sha256: e1ae3815f923d364303195af1472a8c28880b5dad085e42fc8acbb0f8df0e4ad
  patches:
    # The scipy checks are causing issues when importing scipy during the installation
    # procedure
    - ignore-scipy-checks.patch
    # This test requires the git repo to be present, commenting it out
    - comment-environment-test.patch
    # # Networkx 3.3 dropped support for python 3.9, removing this makes the windows build fail
    - limit-networkx.patch  # [py<=39]

build:
  number: 0
  skip: true  # [not win and py<39]
  skip: true  # [win and py<310]
  entry_points:
    - kat3 = finesse.__main__:cli

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cython >=0.29.36
    # extras for cross-compiling
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython >=0.29.36                    # [build_platform != target_platform]
    - numpy >=2                             # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cython >=0.29.36
    - libpython  # [win]
    - numpy >=2
    - pip
    - python
    - scipy >=1.4
    - setuptools
    - setuptools-scm
    - tqdm
    - wheel
    - suitesparse
    - quantiphy
  run:
    - cython >=0.29.36
    - click >=7.1
    - click-default-group >=1.2.2
    - control >0.9  # [not win]
    - control >0.9  # [win and py>310]
    - control <0.10.0  # [win and py<=310]
    - deprecated >=1.2
    - h5py >=3.0
    - matplotlib-base >=3.5  # [not win]
    - numpy >=1.22
    # numpy version issues
    - matplotlib-base >=3.5,<3.9  # [win]
    - more-itertools >=8.7
    - networkx >=2.4  # [py>39]
    - networkx >=2.4,<3.3  # [py<=39] networkx 3.3 doesn't support 3.9 anymore
    - pyspellchecker >=0.6
    - python
    - scipy >=1.4
    - sly >=0.4
    - sympy >=1.6
    - tqdm
    - quantiphy
#    - blockdiag >=3.0  # [py<311] this filter should be removed when https://github.com/conda-forge/funcparserlib-feedstock/pull/13 has been resolved
#    - pillow <10.0 # blockdiag issues: site-packages/blockdiag/imagedraw/png.py:282: DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.

test:
  requires:
    - pytest
    - pytest-benchmark
    - pytest-xdist
    - faker
    - hypothesis
    - docutils
    - black
    - autoflake
    - isort
    - jupyter-sphinx >= 0.4
    - pyyaml
    - pip
    - psutil
  source_files:
    - tests/
    - scripts/
    - environment.yml
    - environment-win.yml
    - pyproject.toml
  imports:
    - finesse
    - finesse.analysis
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - kat3 --help
    # Skipping still runs test_benchmark_creation which fails on linux 
    - rm -rf tests/benchmarks
    # run unit tests
    - python -m pytest tests --import-mode=importlib --benchmark-skip

about:
  home: https://finesse.ifosim.org/
  dev_url: https://gitlab.com/ifosim/finesse/finesse3
  doc_url: https://finesse.ifosim.org/docs/
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: A simulation tool for modelling laser interferometers
  description: |
    Finesse 3 is a Python based interferometer simulation software.

extra:
  recipe-maintainers:
    - danielbrown2
    - duncanmmacleod
    - freise
    - mironleon
