{% set name = "finesse" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/finesse-{{ version }}.tar.gz
  sha256: cabc6c4a660343cd2a4dd77b086122e53c1666fa70421e77f070fcd103e14516
  patches:
    # The scipy checks are causing issues when importing scipy during the installation
    # procedure
    - ignore-scipy-checks.patch
    # This test requires the git repo to be present, commenting it out
    - comment-environment-test.patch
    # dont import ipython at import time
    - move-ipython-import.patch
    - skip-failing-plot-windows.patch

build:
  number: 2
  skip: true  # [py<311]
  entry_points:
    - kat3 = finesse.__main__:cli

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    # extras for cross-compiling
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy >=2                           # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - matplotlib-base >=3.10
  host:
    - cython
    - distutils-activate-mingw  # [win]
    - numpy >=2
    - pip
    - python
    - scipy >=1.4
    # https://gitlab.com/ifosim/finesse/finesse3/-/issues/693
    - setuptools
    - setuptools-scm
    - tqdm
    - wheel
    - suitesparse
    - quantiphy
    - matplotlib-base >=3.10
  run:
    - click >=7.1
    - click-default-group >=1.2.2
    - colorama >=0.4
    - control >=0.9
    - deprecated >=1.2
    - dill
    - h5py >=3.0  # for numpy 2 >= 3.11"
    - matplotlib-base >=3.5  # https://conda-forge.org/docs/maintainer/knowledge_base/#matplotlib
    - networkx >=2.4
    - numpy >=1.20
    - pathos
    - pyspellchecker >=0.6
    - python
    - quantiphy >=2.15
    - scipy >=1.4  #NB: for cython3 SciPy>=1.11.2, see !159#note_1619762810. For numpy 2 SciPy>=1.13.0
    - sly >=0.4
    - sympy >=1.6  # for numpy 2 >= 12.1
    - tqdm >=4.40
test:
  requires:
    - autoflake
    - black
    - docutils
    - faker
    - hypothesis
    - isort
    - jupyter-sphinx >=0.4
    - nbconvert
    - nbformat
    - psutil
    - pytest
    - pytest-benchmark !=5.3.0
    - pytest-xdist
    - pyyaml
  source_files:
    - tests/
    - scripts/
    - environment.yml
    - environment-win.yml
    - pyproject.toml
  imports:
    - finesse
    - finesse.analysis
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - kat3 --help
    # Skipping still runs test_benchmark_creation which fails on linux 
    - rm -rf tests/benchmarks
    # run unit tests
    - python -m pytest tests --import-mode=importlib --benchmark-skip

about:
  home: https://finesse.ifosim.org/
  dev_url: https://gitlab.com/ifosim/finesse/finesse3
  doc_url: https://finesse.ifosim.org/docs/
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: A simulation tool for modelling laser interferometers
  description: |
    Finesse 3 is a Python based interferometer simulation software.

extra:
  recipe-maintainers:
    - msalle
    - JGobeil
    - danielbrown2
    - duncanmmacleod
    - freise
    - mironleon
